name: Do zip on release
on:
  release:
    types:
      - published
  workflow_dispatch:
      
jobs:
  do_zip:
    secrets: inherit
    uses: jjerhub/Utilities.GithubWorkflows/.github/workflows/MakeRailloaderModZip.yml@v1.0.0
    with:
      mod-name: 'AJIX_Extended'
